DmitryTsepelev/graphql-ruby-fragment_cache

.rbnextrc, Rakefile, gemfiles/rubocop.gemfile, graphql-ruby-fragment_cache.gemspec, lib/graphql-fragment_cache.rb
The main goal of this PR is to make it possible to install a gem from source even in older Rubies.
That could be achieved by using a new [auto-transpiling](https://github.com/ruby-next/ruby-next#transpiled-files-vs-vsc-vs-installing-from-source) Ruby Next feature.
Also, we can make Ruby Next installed automatically by making it a runtime dependency in case the gem is loaded from source (we check for the presence of the `.git` folder for that).
=> Upgrade ruby-next

CHANGELOG.md, lib/graphql/fragment_cache/rails/cache_key_builder.rb, spec/graphql/fragment_cache/rails/cache_key_builder_spec.rb
I think this fixes #36. It seems to work for us, it hasn't been extensively tested yet. 
I think the README might be out of date as well for the order of operations, under the section "The way cache key part is generated for the passed argument"
=> Add Rails cache key calls

README.md, lib/graphql/fragment_cache/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb
As discussed in #49, this allows specifying the object's cache key.
=> Add object_cache_key to CacheKeyBuilder

lib/graphql/fragment_cache/fragment.rb
Hi again! 👋 In asynchronous situations, it is possible for `context`'s runtime `final_value` to return `nil`, even when there was previously a value present. This resulted in an error in `Fragment#value` or a quietly dead thread. 
I asked rmosolgo if there was a safer way to retrieve the final result value in `after_query` and his suggestion was to pull the data from the query result. We've been running with this code for a couple of days and it appears to have resolved the issue. 
~We could also check for both...~ Nevermind, the old code that this replaces can result in receiving unresolved promises or other async values awaiting `sync`.
=> Use thread-safe query result for final_value

lib/graphql/fragment_cache/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb, spec/support/test_schema.rb
~(This is a draft because of a probable refactor, [see my comment in the files](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/pull/54/files))~
We have some nested cache fragments, and we had an issue where the parent keys of the children are not including children's nested hard-coded arguments. This results in queries with the same AST but different internal arguments using the same cache key, which is not correct. For example:
```graphql
query something($id: ID!) {
thing(id: $id) {
internalThing(parameter: "words")
}
}
```
and 
```graphql
query something($id: ID!) {
thing(id: $id) {
internalThing(anotherParameter: "TEST")
}
}
```
will have the same cache key.
=> Include arguments in selections_cache_key

README.md, lib/graphql/fragment_cache.rb, spec/graphql/fragment_cache_spec.rb
This PR adds the following alternative way to configure the gem (typically in a Rails initializer):
```ruby
GraphQL::FragmentCache.configure do |config|
config.cache_store = MyCacheStore.new
end
```
The main benefit is that it is less verbose once you start having multiple configuration options (like https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/pull/64):
```ruby
GraphQL::FragmentCache.configure do |config|
config.cache_store = MyCacheStore.new
config.option2 = "foo"
config.option3 = "bar"
end
```
I also like this notation because its is used by many gems, so it feels familiar.
=> Add a configure block notation

README.md, lib/graphql/fragment_cache.rb, lib/graphql/fragment_cache/cache_key_builder.rb, lib/graphql/fragment_cache/rails/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb
This PR allows you to configure a namespace which will be prefixed to all cache keys:
```ruby
GraphQL::FragmentCache.namespace = 'graphql'
```
This can be useful if the cache store is shared, allows listing keys, and you want to to differentiate between the graphql-fragment_cache ones and the rest. For example in Redis:
```ruby
pry(main)> $redis.keys
=> [
"graphql/7ace5027bfa9cd0314b3e310d3ae10921a065ef9",
"some-other-unrelated-key"
]
```
Or if for some reason you want to clear all graphql fragment cache keys: 
```ruby
Rails.cache.delete_matched('graphql/*') # works if your cache store is Redis
```
Currently this PR does not set a default namespace, but I think there should be one like `"graphql"` maybe. Let me know what you think (it is very easy to add) otherwise this PR can be shipped …
=> Add a cache namespace

README.md, lib/graphql/fragment_cache/fragment.rb, spec/graphql/fragment_cache/field_extensions_spec.rb
Useful for cache warmers if you want to renew the cache.
Similar to `rails`' `ActiveSupport::Cache::Store#fetch`'s [`force: true`](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch) option and `graphql-cache`'s [`force_cache`](https://github.com/stackshareio/graphql-cache/#forcing-the-cache) option.
=> Add a way to force a cache miss

README.md, lib/graphql/fragment_cache.rb, lib/graphql/fragment_cache/field_extension.rb, lib/graphql/fragment_cache/object_helpers.rb, spec/graphql/fragment_cache/object_helpers_spec.rb
I find myself needing to set the same options to all my `cache_fragment:` or `#cache_fragment`. This PR allows you to configure default options globally instead:
```ruby
config.default_options = {
expires_in: 1.hour,
schema_cache_key: nil,
cache_key: :object
}
```
These options can be overriden, for example by doing `cache_fragment(expires_in: 5.minutes)`.
By the way, setting `schema_cache_key: nil` as a default option is a low-level way to fix #9.
=> Add default options

lib/graphql/fragment_cache/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb, spec/graphql/fragment_cache/object_helpers_spec.rb
Unique cache keys are already generated if a field containing selections is aliased. This PR also adds uniqueness for aliases on individual selections. I couldn't find a way to get to the aliases other than going through the ast_nodes, open to alternatives if you're aware of them!
=> Add selection alias to cache keys

lib/graphql/fragment_cache/fragment.rb, spec/graphql/fragment_cache/fragment_spec.rb
When the context `{renew_cache: true}` is passed to a cached query in an application that is using a `cache_store` that supports `read_multi` (e.g. Redis) the cache is not cleared and `{renew_cache: true}` is ignored.
When the context `{renew_cache: true}` is passed to a cached query the cache is renewed.
This commit fixes the above issue by adding logic that checks for `{renew_cache: true}` in the context of fragments passed to the `read_multi` method and returns `nil` for their value so that cache is refreshed. With this change, there is feature parity between cache stores that support `read_multi` and those that don't.
=> Fix Renew Cache Read Multi Bug

CHANGELOG.md, README.md, lib/graphql/fragment_cache/field_extension.rb, spec/graphql/fragment_cache/field_extensions_spec.rb, spec/support/test_schema.rb
We persisted the result of the first execution of the passed Proc and used it for all subsequent calls — 😬
Also added support for passing Symbols to `if` and `unless`:
```ruby
field :collection, resolver:  SomeResolver, cache_fragment: {if: :anonymous_user?}
```
=> Fix conditional caching

CHANGELOG.md, README.md, lib/graphql/fragment_cache.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb, spec/graphql/fragment_cache/rails/cache_key_builder_spec.rb
I don't know if you want this, but I feel like prefixing keys with the "graphql" namespace should be the default.
=> Use a "graphql" cache namespace by default

CHANGELOG.md, README.md, lib/graphql/fragment_cache/field_extension.rb, spec/graphql/fragment_cache/field_extensions_spec.rb
Making `cache_key` support procs is useful when you want complete control over the cache key.
For example:
```ruby
field :posts,
Types::Objects::PostType.connection_type,
cache_fragment: { cache_key: -> { object.posts.maximum(:created_at) } }
field :comments,
Types::Objects::CommentType.connection_type,
cache_fragment: { cache_key: -> { [current_tenant.id, object] } }
field :activities,
Types::Objects::ActivityType.connection_type,
cache_fragment: { cache_key: -> { object.id } }
```
It is already possible to have complete control over the cache key with the `cache_fragment(whatever_key_you_want_here) { post }` syntax.
This PR makes it possible to do the same with with the `cache_fragment: { cache_key: -> { whatever_key_you_want_here } }` syntax.
What do you think?
_PS: similarly to #85 we …
=> Make `cache_key` option support procs

CHANGELOG.md, lib/graphql/fragment_cache/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb, spec/graphql/fragment_cache/rails/cache_key_builder_spec.rb
Show the non-fingerprinted simple path in the cache key to make it more readable. The simple path is just the path but without parameters.
The cache key is now made up of 4 parts: namespace, simple path cache key, implicit cache key, and object cache key.
Each part is delimited by `/`, and within each part the delimiter is `-`. This way it is easy to see at a glance where the parts are. Here are some examples keys:
```
[41] pry(main)> $redis.keys('graphql*').sort
[
[ 0] "graphql/post/766b6ccc10ab9495379351ee8beafea5c6007503/1595-mycorp",
[ 1] "graphql/currentTenant-activities/8fb06e96554aadb59acc95055d94ac32e35ad383/1595-mycorp",
[ 2] "graphql/currentTenant-posts/f328972b1d41071057c1e9b2ba2942376ead0def/posts-query-5f6b140cd0b110df8830cb806289afae-6-20220927164337385299-mycorp",
[ 3] …
```
=> Make cache keys human-readable

lib/graphql/fragment_cache/cache_key_builder.rb, spec/graphql/fragment_cache/cache_key_builder_spec.rb
The change in #92 now causes an error if `path_cache_key` is nil.
This PR fixes it.
```
undefined method `split' for nil:NilClass
path_cache_key.split("(").first
^^^^^^
/usr/local/bundle/gems/graphql-fragment_cache-1.18.1/lib/graphql/fragment_cache/cache_key_builder.rb:180:in `simple_path_cache_key'
/usr/local/bundle/gems/graphql-fragment_cache-1.18.1/lib/graphql/fragment_cache/cache_key_builder.rb:142:in `build'
/usr/local/bundle/gems/graphql-fragment_cache-1.18.1/lib/graphql/fragment_cache/cache_key_builder.rb:125:in `call'
/usr/local/bundle/gems/graphql-fragment_cache-1.18.1/lib/graphql/fragment_cache/fragment.rb:56:in `cache_key'
/usr/local/bundle/gems/graphql-fragment_cache-1.18.1/lib/graphql/fragment_cache/fragment.rb:20:in `block in read_multi' …
```
=> Fix an error when path_cache_key is nil

README.md
Looks like the we're suggesting the wrong work around here. Accoring to https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/5628ad30e801fa8f772286e7327fdeac746969ce/lib/graphql/fragment_cache/cache_key_builder.rb#L194
its the `path_cache_key` that needs to be passed
=> Fixes incorrect workaround for look ahead limitation

lib/graphql/fragment_cache.rb
With the latest version of the `graphql` gem, you get this warning:
```
Schema.instrument is deprecated, use `trace_with` instead: https://graphql-ruby.org/queries/tracing.html"
```
This PR fixes #107
=> Use trace_with instead of deprecated instrument method 

lib/graphql/fragment_cache/railtie.rb, spec/graphql/fragment_cache/rails/railtie_spec.rb
With Rails 7.1, we will see warning about cache format like below.
To solve it, set the cache format version according to Rails configuration.
```bash
$ rails c
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
(called from <class:Application> at /Users/.../config/application.rb:63)
```
=> Fix deprecation warning for cache_format_version in Rails 7.1

lib/graphql/fragment_cache/railtie.rb
As per https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
Rails.application.config.active_support.cache_format_version returns nil so the explicit delaration of `7.0` will do the thing
=> Fix deprecation

lib/graphql/fragment_cache/railtie.rb, spec/graphql/fragment_cache/cacher_spec.rb, spec/graphql/fragment_cache/rails/railtie_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
Fixes #114 
`Rail.application` was always evaluating to `nil` before as the code wasn't running in an initializer.
I changed the approach slightly to be less intrusive: now we simply initialize the cache store with a non-deprecated serializer, instead of modifying the `ActiveSupport.cache_format_version` configuration.
---
NOTE: after my change, if the user is on Rails >= 7 and didn't configure `ActiveSupport::Cache.format_version`, if they manually change the store (e.g.: `Rails.application.config.graphql_fragment_cache = :memory_store`), that will raise a ActiveSupport warning.
I believe this behaviour is appropriate - the user should set an appropriate cache_format_version before setting the cache store.
=> Fix warning on ActiveSupport::Cache.format_version

README.md
Providing a `path_cache_key` will resolve the `Lookahead` problem, per the documentation. However, the code example is showing a `query_cache_key`, not the `path_cache_key`. 
This PR fixes that.
=> Update README.md - correct path_cache_key code example

README.md, lib/graphql/fragment_cache.rb, lib/graphql/fragment_cache/fragment.rb
Relates to: https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/issues/124
This attempts to determine if there was a cache hit and then records that along with cache key, operation name and path attributes.
By default, this calls `cache_lookup_event()` which has no action.
Implementing the gem in the parent application would enable monitoring (or whatever) of these cache hits. In our case, we probably just want to increment a cache hit or miss metric tagged with the path and operation name.
```ruby
module GraphQL
module FragmentCache
class Fragment
def self.cache_lookup_event(**args)
end
end
end
end
```
=> Introduce cache lookup instrumentation hook

lib/graphql/fragment_cache/railtie.rb
The problem was caused by `Cacher`: it could not write data because of the error caused by the cache format. This affected only NullStore I guess
Fixes #126
=> Fix nullstore serializer

CHANGELOG.md, README.md, lib/graphql/fragment_cache/fragment.rb, lib/graphql/fragment_cache/object_helpers.rb, lib/graphql/fragment_cache/schema/lazy_cache_resolver.rb, spec/graphql/fragment_cache/object_helpers_spec.rb, spec/graphql/fragment_cache/schema/lazy_cache_resolver_spec.rb, spec/support/models/user.rb, spec/support/test_schema.rb
=> Dataloader support

CHANGELOG.md, lib/graphql/fragment_cache/graphql_ruby_version.rb, lib/graphql/fragment_cache/schema/tracer.rb
=> Remove new_connections? check for gql > 2.3.10 in Tracer
